export const htmlTemplate = '<ul class="container">'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="0"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="1"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="2"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="3"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="4"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="5"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="6"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="7"> class="button">Comments</button>'
+ '</li>'
+ '<li class="item">'
+ '<div class="img-container">'
+ '<img class="img" src="">'
+ '</div>'
+ '<div class="like-container">'
+ '<p class="title"></p>'
+ '<i class="far fa-heart icon-heart"></i>'
+ '<p class="likes"></p>'
+ '</div>'
+ '<button data-id="8"> class="button">Comments</button>'
+ '</li>'
+ '</ul>';
